version: '2'

services:
  minio:
    image: 'bitnami/minio:2020'
    container_name: minio
    ports:
      - '2023:9000'
      - '2020:9001'
    restart: always
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=password
    volumes:
      - ./data/:/data
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge